---
version: "3"
services:
  food:
    container_name: food-cont
    build: ./food/
    ports:
      - "8080:80"
  instamart:
    container_name: instamart-cont
    build: ./instamart/
    ports:
      - "8081:80"
  help:
    container_name: help-cont
    build: ./help/
    ports:
      - "8082:80"
